"""
===============================================================================
Support Intelligence Platform

Module  : Dashboard Builder
Version : 4.1

Builds the executive reporting workbook using outputs generated by

• Analytics Engine
• Executive Insights Engine
• Recommendation Engine
• Health Engine
• Renewal Risk Engine
• Voice of Customer Engine

Author : Nischal
===============================================================================
"""

from pathlib import Path
from datetime import datetime

import pandas as pd

from openpyxl import Workbook
from openpyxl.styles import (
    Font,
    PatternFill,
    Border,
    Side,
    Alignment
)
from openpyxl.chart import (
    PieChart,
    BarChart,
    LineChart,
    Reference
)
from openpyxl.chart.label import DataLabelList


class DashboardBuilder:

    """
    Executive Dashboard Builder
    """

    # ==================================================================
    # Constructor
    # ==================================================================

    def __init__(
        self,
        analytics,
        insights,
        recommendations,
        health,
        renewal,
        voc
    ):

        self.analytics = analytics
        self.insights = insights
        self.recommendations = recommendations
        self.health = health
        self.renewal = renewal
        self.voc = voc

        self.workbook = Workbook()

        if self.workbook.sheetnames:
            self.workbook.remove(self.workbook.active)

        self.create_styles()

    # ==================================================================
    # Styles
    # ==================================================================

    def create_styles(self):

        self.title_fill = PatternFill(
            fill_type="solid",
            fgColor="1F4E78"
        )

        self.header_fill = PatternFill(
            fill_type="solid",
            fgColor="D9EAD3"
        )

        self.blue_fill = PatternFill(
            fill_type="solid",
            fgColor="D9EAF7"
        )

        self.green_fill = PatternFill(
            fill_type="solid",
            fgColor="C6EFCE"
        )

        self.yellow_fill = PatternFill(
            fill_type="solid",
            fgColor="FFF2CC"
        )

        self.red_fill = PatternFill(
            fill_type="solid",
            fgColor="F4CCCC"
        )

        self.grey_fill = PatternFill(
            fill_type="solid",
            fgColor="EDEDED"
        )

        self.title_font = Font(
            bold=True,
            size=18,
            color="FFFFFF"
        )

        self.section_font = Font(
            bold=True,
            size=13
        )

        self.header_font = Font(
            bold=True,
            size=11
        )

        self.normal_font = Font(
            size=10
        )

        thin = Side(style="thin")

        self.border = Border(
            left=thin,
            right=thin,
            top=thin,
            bottom=thin
        )

    # ==================================================================
    # Common Sheet Styling
    # ==================================================================

    def style_sheet(
        self,
        worksheet,
        title
    ):

        worksheet.merge_cells("A1:H1")

        worksheet["A1"] = "SUPPORT INTELLIGENCE PLATFORM"
        worksheet["A1"].fill = self.title_fill
        worksheet["A1"].font = self.title_font
        worksheet["A1"].alignment = Alignment(
            horizontal="center"
        )

        worksheet["A2"] = title
        worksheet["A2"].font = self.section_font

        worksheet["H2"] = datetime.now().strftime(
            "%d-%b-%Y %H:%M"
        )

        worksheet["H2"].alignment = Alignment(
            horizontal="right"
        )

    # ==================================================================
    # Table Formatting
    # ==================================================================

    def format_table(
        self,
        worksheet,
        header_row
    ):

        for cell in worksheet[header_row]:

            cell.fill = self.header_fill
            cell.font = self.header_font
            cell.border = self.border
            cell.alignment = Alignment(
                horizontal="center",
                vertical="center"
            )

        for row in worksheet.iter_rows(
            min_row=header_row + 1
        ):

            for cell in row:

                cell.border = self.border
                cell.alignment = Alignment(
                    vertical="top",
                    wrap_text=True
                )

        worksheet.freeze_panes = f"A{header_row + 1}"
        worksheet.auto_filter.ref = worksheet.dimensions

    # ==================================================================
    # Auto Width
    # ==================================================================

    def auto_width(
        self,
        worksheet
    ):

        for column_cells in worksheet.columns:

            try:
                letter = column_cells[0].column_letter
            except Exception:
                continue

            width = 0

            for cell in column_cells:

                try:
                    width = max(
                        width,
                        len(str(cell.value))
                    )
                except Exception:
                    pass

            worksheet.column_dimensions[
                letter
            ].width = min(width + 3, 40)

    # ==================================================================
    # Generic DataFrame Writer
    # ==================================================================

    def dataframe_to_sheet(
        self,
        sheet_name,
        dataframe
    ):

        if dataframe is None or dataframe.empty:
            return None

        worksheet = self.workbook.create_sheet(
            sheet_name[:31]
        )

        self.style_sheet(
            worksheet,
            sheet_name
        )

        start_row = 4

        for col, column_name in enumerate(
            dataframe.columns,
            start=1
        ):

            worksheet.cell(
                row=start_row,
                column=col,
                value=column_name
            )

        for row_index, row in enumerate(
            dataframe.itertuples(index=False),
            start=start_row + 1
        ):

            for col, value in enumerate(
                row,
                start=1
            ):

                worksheet.cell(
                    row=row_index,
                    column=col,
                    value=value
                )

        self.format_table(
            worksheet,
            start_row
        )

        self.auto_width(
            worksheet
        )

        return worksheet
    # ==================================================================
    # Executive Summary
    # ==================================================================

    def build_executive_summary(self):

        print("Creating Executive Summary...")

        ws = self.workbook.create_sheet(
            "Executive Summary",
            0
        )

        self.style_sheet(
            ws,
            "Executive Dashboard"
        )

        kpis = getattr(
            self.analytics,
            "kpis",
            {}
        )

        # ==============================================================
        # KPI SECTION
        # ==============================================================

        ws["A4"] = "KEY PERFORMANCE INDICATORS"
        ws["A4"].font = self.section_font

        metrics = [

            ("Total Tickets",
             kpis.get("Total Tickets", 0)),

            ("Customer Tickets",
             kpis.get("Customer Tickets", 0)),

            ("Operational Tickets",
             kpis.get("Operational Tickets", 0)),

            ("Open Tickets",
             kpis.get("Open Tickets", 0)),

            ("Pending Tickets",
             kpis.get("Pending Tickets", 0)),

            ("Resolved Tickets",
             kpis.get("Resolved Tickets", 0)),

            ("Closed Tickets",
             kpis.get("Closed Tickets", 0)),

            ("Average Confidence",
             f"{kpis.get('Average Confidence',0):.2f}%"),

            ("Products Covered",
             kpis.get("Products Covered",0)),

            ("Categories Covered",
             kpis.get("Categories Covered",0))

        ]

        row = 6

        for metric, value in metrics:

            c1 = ws.cell(row=row, column=1, value=metric)
            c2 = ws.cell(row=row, column=2, value=value)

            c1.fill = self.blue_fill
            c1.font = self.header_font
            c1.border = self.border

            c2.border = self.border

            row += 1

        # ==============================================================
        # CUSTOMER HEALTH
        # ==============================================================

        row += 2

        ws.cell(
            row=row,
            column=1,
            value="CUSTOMER HEALTH"
        ).font = self.section_font

        health = self.health.results

        distribution = (

            health["Health Status"]

            .value_counts()

            .sort_index()

        )

        row += 2

        ws.cell(row=row,column=1,value="Status")
        ws.cell(row=row,column=2,value="Customers")

        row += 1

        for status, count in distribution.items():

            c1 = ws.cell(
                row=row,
                column=1,
                value=status
            )

            c2 = ws.cell(
                row=row,
                column=2,
                value=int(count)
            )

            c1.border = self.border
            c2.border = self.border

            if status in [

                "Excellent",

                "Healthy"

            ]:

                c1.fill = self.green_fill

            elif status in [

                "Good",

                "Watch"

            ]:

                c1.fill = self.yellow_fill

            else:

                c1.fill = self.red_fill

            row += 1

        # ==============================================================
        # RENEWAL RISK
        # ==============================================================

        row += 2

        ws.cell(
            row=row,
            column=1,
            value="RENEWAL RISK"
        ).font = self.section_font

        risk = (

            self.renewal.results

            ["Risk Level"]

            .value_counts()

            .sort_index()

        )

        row += 2

        ws.cell(row=row,column=1,value="Risk")
        ws.cell(row=row,column=2,value="Customers")

        row += 1

        for level, count in risk.items():

            c1 = ws.cell(
                row=row,
                column=1,
                value=level
            )

            c2 = ws.cell(
                row=row,
                column=2,
                value=int(count)
            )

            c1.border = self.border
            c2.border = self.border

            if level == "Low":

                c1.fill = self.green_fill

            elif level == "Medium":

                c1.fill = self.yellow_fill

            else:

                c1.fill = self.red_fill

            row += 1

        # ==============================================================
        # EXECUTIVE TOTALS
        # ==============================================================

        row += 3

        ws.cell(
            row=row,
            column=1,
            value="EXECUTIVE TOTALS"
        ).font = self.section_font

        row += 2

        executive = [

            (

                "Insights Generated",

                len(self.insights.insights)

            ),

            (

                "Recommendations",

                len(self.recommendations.generated)

            ),

            (

                "Voice of Customer Observations",

                len(self.voc.report)

            ),

            (

                "Customers Analysed",

                len(self.health.results)

            )

        ]

        for title, value in executive:

            c1 = ws.cell(
                row=row,
                column=1,
                value=title
            )

            c2 = ws.cell(
                row=row,
                column=2,
                value=value
            )

            c1.fill = self.grey_fill
            c1.font = self.header_font
            c1.border = self.border

            c2.border = self.border

            row += 1

        self.auto_width(ws)

    # ==================================================================
    # Analytics Sheets
    # ==================================================================

    def build_analytics_sheets(self):

        print("Creating Analytics Sheets...")

        summary = getattr(
            self.analytics,
            "summary",
            {}
        )

        if not isinstance(summary, dict):

            return

        for sheet_name, dataframe in summary.items():

            if sheet_name == "Executive KPIs":

                continue

            if not isinstance(dataframe, pd.DataFrame):

                continue

            if dataframe.empty:

                continue

            self.write_analytics_sheet(
                sheet_name,
                dataframe
            )

    # ==================================================================
    # Analytics Sheet Writer
    # ==================================================================

    def write_analytics_sheet(
        self,
        sheet_name,
        dataframe
    ):

        print(f"  • {sheet_name}")

        worksheet = self.workbook.create_sheet(
            sheet_name[:31]
        )

        self.style_sheet(
            worksheet,
            sheet_name
        )

        worksheet["A4"] = f"{sheet_name} Summary"
        worksheet["A4"].font = self.section_font

        start_row = 6

        for col, column in enumerate(
            dataframe.columns,
            start=1
        ):

            cell = worksheet.cell(
                row=start_row,
                column=col,
                value=column
            )

            cell.fill = self.header_fill
            cell.font = self.header_font
            cell.border = self.border
            cell.alignment = Alignment(
                horizontal="center",
                vertical="center"
            )

        current_row = start_row + 1

        for row in dataframe.itertuples(index=False):

            for col, value in enumerate(
                row,
                start=1
            ):

                cell = worksheet.cell(
                    row=current_row,
                    column=col,
                    value=value
                )

                cell.border = self.border
                cell.alignment = Alignment(
                    vertical="top",
                    wrap_text=True
                )

            current_row += 1

        worksheet.cell(
            row=current_row + 2,
            column=1,
            value="Total Records"
        ).font = self.header_font

        worksheet.cell(
            row=current_row + 2,
            column=2,
            value=len(dataframe)
        )

        worksheet.freeze_panes = "A7"
        worksheet.auto_filter.ref = worksheet.dimensions

        self.auto_width(worksheet)

    # ==================================================================
    # Analytics Index
    # ==================================================================

    def build_analytics_index(self):

        ws = self.workbook.create_sheet(
            "Analytics Index"
        )

        self.style_sheet(
            ws,
            "Analytics Index"
        )

        ws["A4"] = "Available Analytics Reports"
        ws["A4"].font = self.section_font

        ws["A6"] = "Worksheet"
        ws["B6"] = "Rows"

        ws["A6"].fill = self.header_fill
        ws["B6"].fill = self.header_fill

        ws["A6"].font = self.header_font
        ws["B6"].font = self.header_font

        row = 7

        summary = getattr(
            self.analytics,
            "summary",
            {}
        )

        for name, dataframe in summary.items():

            if not isinstance(dataframe, pd.DataFrame):

                continue

            ws.cell(row=row, column=1, value=name)
            ws.cell(row=row, column=2, value=len(dataframe))

            row += 1

        self.auto_width(ws)

    # ==================================================================
    # Build Analytics
    # ==================================================================

    def build_analytics(self):

        self.build_analytics_index()

        self.build_analytics_sheets()
    # ==================================================================
    # Executive Insights
    # ==================================================================

    def build_insights_sheet(self):

        print("Creating Executive Insights...")

        insights = getattr(
            self.insights,
            "insights",
            []
        )

        if len(insights) == 0:

            print("No Executive Insights found.")

            return

        df = pd.DataFrame(insights)

        self.dataframe_to_sheet(
            "Executive Insights",
            df
        )

    # ==================================================================
    # Recommendation Register
    # ==================================================================

    def build_recommendation_sheet(self):

        print("Creating Recommendations...")

        recommendations = getattr(
            self.recommendations,
            "generated",
            []
        )

        if len(recommendations) == 0:

            print("No Recommendations found.")

            return

        df = pd.DataFrame(recommendations)

        self.dataframe_to_sheet(
            "Recommendations",
            df
        )

    # ==================================================================
    # Customer Health
    # ==================================================================

    def build_health_sheet(self):

        print("Creating Customer Health...")

        df = getattr(
            self.health,
            "results",
            pd.DataFrame()
        )

        if df.empty:

            print("No Customer Health data found.")

            return

        self.dataframe_to_sheet(
            "Customer Health",
            df
        )

    # ==================================================================
    # Renewal Risk
    # ==================================================================

    def build_renewal_sheet(self):

        print("Creating Renewal Risk...")

        df = getattr(
            self.renewal,
            "results",
            pd.DataFrame()
        )

        if df.empty:

            print("No Renewal Risk data found.")

            return

        self.dataframe_to_sheet(
            "Renewal Risk",
            df
        )

    # ==================================================================
    # Voice of Customer
    # ==================================================================

    def build_voc_sheet(self):

        print("Creating Voice of Customer...")

        report = getattr(
            self.voc,
            "report",
            []
        )

        if len(report) == 0:

            print("No Voice of Customer observations found.")

            return

        df = pd.DataFrame(report)

        self.dataframe_to_sheet(
            "Voice of Customer",
            df
        )

    # ==================================================================
    # Executive Workbook Summary
    # ==================================================================

    def build_business_reports(self):

        """
        Creates all business reporting worksheets.
        """

        self.build_insights_sheet()
        self.build_recommendation_sheet()
        self.build_health_sheet()
        self.build_renewal_sheet()
        self.build_voc_sheet()

    # ==================================================================
    # Department Dashboard Helper
    # ==================================================================

    def build_department_dashboard(
        self,
        owner,
        sheet_name
    ):

        print(f"Creating {sheet_name}...")

        recommendations = getattr(
            self.recommendations,
            "generated",
            []
        )

        if len(recommendations) == 0:
            return

        df = pd.DataFrame(recommendations)

        if "Owner" not in df.columns:
            return

        df = df[df["Owner"] == owner]

        ws = self.workbook.create_sheet(sheet_name)

        self.style_sheet(
            ws,
            sheet_name
        )

        ws["A4"] = f"{owner} Dashboard"
        ws["A4"].font = self.section_font

        summary = [

            ("Total Recommendations", len(df)),
            ("Priority P1", len(df[df["Priority"] == "P1"])),
            ("Priority P2", len(df[df["Priority"] == "P2"])),
            ("Priority P3", len(df[df["Priority"] == "P3"]))

        ]

        row = 6

        for metric, value in summary:

            c1 = ws.cell(row=row, column=1, value=metric)
            c2 = ws.cell(row=row, column=2, value=value)

            c1.fill = self.blue_fill
            c1.font = self.header_font
            c1.border = self.border
            c2.border = self.border

            row += 1

        row += 2

        columns = [

            "Priority",
            "Title",
            "Metric",
            "Actual",
            "Threshold",
            "Expected Benefit",
            "Business Impact",
            "Status"

        ]

        for col, column in enumerate(columns, start=1):

            cell = ws.cell(
                row=row,
                column=col,
                value=column
            )

            cell.fill = self.header_fill
            cell.font = self.header_font
            cell.border = self.border
            cell.alignment = Alignment(horizontal="center")

        row += 1

        for _, record in df.iterrows():

            for col, column in enumerate(columns, start=1):

                cell = ws.cell(
                    row=row,
                    column=col,
                    value=record.get(column, "")
                )

                cell.border = self.border

            row += 1

        ws.freeze_panes = "A13"
        ws.auto_filter.ref = ws.dimensions

        self.auto_width(ws)

    # ==================================================================
    # Department Dashboards
    # ==================================================================

    def build_engineering_dashboard(self):

        self.build_department_dashboard(
            owner="Engineering",
            sheet_name="Engineering Dashboard"
        )

    def build_product_dashboard(self):

        self.build_department_dashboard(
            owner="Product",
            sheet_name="Product Dashboard"
        )

    def build_customer_success_dashboard(self):

        self.build_department_dashboard(
            owner="Customer Success",
            sheet_name="Customer Success Dashboard"
        )

    def build_finance_dashboard(self):

        self.build_department_dashboard(
            owner="Finance",
            sheet_name="Finance Dashboard"
        )

    def build_support_dashboard(self):

        self.build_department_dashboard(
            owner="Support",
            sheet_name="Support Dashboard"
        )

    def build_department_dashboards(self):

        print("Creating Department Dashboards...")

        self.build_engineering_dashboard()
        self.build_product_dashboard()
        self.build_customer_success_dashboard()
        self.build_finance_dashboard()
        self.build_support_dashboard()
    # ==================================================================
    # Chart Helpers
    # ==================================================================

    def create_pie_chart(
        self,
        worksheet,
        title,
        start_row,
        end_row,
        category_col,
        value_col,
        position
    ):

        labels = Reference(
            worksheet,
            min_col=category_col,
            min_row=start_row,
            max_row=end_row
        )

        data = Reference(
            worksheet,
            min_col=value_col,
            min_row=start_row - 1,
            max_row=end_row
        )

        chart = PieChart()

        chart.title = title
        chart.height = 8
        chart.width = 10

        chart.add_data(
            data,
            titles_from_data=True
        )

        chart.set_categories(labels)

        chart.dataLabels = DataLabelList()
        chart.dataLabels.showPercent = True
        chart.dataLabels.showVal = True

        worksheet.add_chart(
            chart,
            position
        )

    # ==================================================================

    def create_bar_chart(
        self,
        worksheet,
        title,
        start_row,
        end_row,
        category_col,
        value_col,
        position
    ):

        labels = Reference(
            worksheet,
            min_col=category_col,
            min_row=start_row,
            max_row=end_row
        )

        data = Reference(
            worksheet,
            min_col=value_col,
            min_row=start_row - 1,
            max_row=end_row
        )

        chart = BarChart()

        chart.title = title
        chart.height = 8
        chart.width = 14

        chart.add_data(
            data,
            titles_from_data=True
        )

        chart.set_categories(labels)

        worksheet.add_chart(
            chart,
            position
        )

    # ==================================================================

    def create_horizontal_chart(
        self,
        worksheet,
        title,
        start_row,
        end_row,
        category_col,
        value_col,
        position
    ):

        labels = Reference(
            worksheet,
            min_col=category_col,
            min_row=start_row,
            max_row=end_row
        )

        data = Reference(
            worksheet,
            min_col=value_col,
            min_row=start_row - 1,
            max_row=end_row
        )

        chart = BarChart()

        chart.type = "bar"

        chart.title = title
        chart.height = 8
        chart.width = 16

        chart.add_data(
            data,
            titles_from_data=True
        )

        chart.set_categories(labels)

        chart.legend = None

        worksheet.add_chart(
            chart,
            position
        )

    # ==================================================================
    # Executive Charts
    # ==================================================================

    def build_chart_dashboard(self):

        print("Creating Executive Charts...")

        ws = self.workbook.create_sheet(
            "Executive Charts"
        )

        self.style_sheet(
            ws,
            "Executive Visual Dashboard"
        )

        summary = getattr(
            self.analytics,
            "summary",
            {}
        )

        chart_positions = [
            "A3", "J3",
            "A22", "J22",
            "A41", "J41",
            "A60", "J60",
            "A79", "J79"
        ]

        datasets = [

            (
                "Products",
                "Product",
                "Tickets",
                "Product Distribution",
                self.create_pie_chart
            ),

            (
                "Categories",
                "Category",
                "Tickets",
                "Ticket Categories",
                self.create_bar_chart
            ),

            (
                "AI",
                None,
                None,
                "AI Feature Distribution",
                self.create_bar_chart
            ),

            (
                "Customers",
                None,
                "Tickets",
                "Top Customers",
                self.create_horizontal_chart
            ),

            (
                "Monthly Trend",
                "Month",
                "Tickets",
                "Monthly Trend",
                self.create_bar_chart
            )

        ]

        current_row = 2
        chart_index = 0

        for (
            dataset_name,
            category_name,
            value_name,
            chart_title,
            chart_builder
        ) in datasets:

            if dataset_name not in summary:

                continue

            df = summary[dataset_name]

            if df.empty:

                continue

            if dataset_name == "Customers":

                df = df.head(10)

            start = current_row

            category_column = category_name or df.columns[0]
            value_column = value_name or df.columns[1]

            ws.cell(start, 1, category_column)
            ws.cell(start, 2, value_column)

            for i, row in enumerate(
                df.itertuples(index=False),
                start=start + 1
            ):

                ws.cell(i, 1, row[0])
                ws.cell(i, 2, row[1])

            chart_builder(
                ws,
                chart_title,
                start + 1,
                start + len(df),
                1,
                2,
                chart_positions[chart_index]
            )

            current_row += len(df) + 6
            chart_index += 1

            if chart_index >= len(chart_positions):

                break

        self.auto_width(ws)

    # ==================================================================
    # Business Charts
    # ==================================================================

    def build_business_charts(self):

        print("Creating Business Charts...")

        ws = self.workbook["Executive Charts"]

        current_row = ws.max_row + 5

        # ==============================================================
        # Customer Health
        # ==============================================================

        health = (
            self.health.results
            .groupby("Health Status")
            .size()
            .reset_index(name="Customers")
        )

        ws.cell(current_row, 1, "Health Status")
        ws.cell(current_row, 2, "Customers")

        header = current_row
        current_row += 1

        for _, row in health.iterrows():

            ws.cell(current_row, 1, row["Health Status"])
            ws.cell(current_row, 2, row["Customers"])

            current_row += 1

        self.create_pie_chart(
            ws,
            "Customer Health",
            header + 1,
            current_row - 1,
            1,
            2,
            "A98"
        )

        current_row += 4

        # ==============================================================
        # Renewal Risk
        # ==============================================================

        renewal = (
            self.renewal.results
            .groupby("Risk Level")
            .size()
            .reset_index(name="Customers")
        )

        ws.cell(current_row, 1, "Risk Level")
        ws.cell(current_row, 2, "Customers")

        header = current_row
        current_row += 1

        for _, row in renewal.iterrows():

            ws.cell(current_row, 1, row["Risk Level"])
            ws.cell(current_row, 2, row["Customers"])

            current_row += 1

        self.create_pie_chart(
            ws,
            "Renewal Risk",
            header + 1,
            current_row - 1,
            1,
            2,
            "J98"
        )

        self.auto_width(ws)
            # ==================================================================
    # Conditional Formatting
    # ==================================================================

    def apply_conditional_formatting(self):

        print("Applying Workbook Formatting...")

        for ws in self.workbook.worksheets:

            # ----------------------------------------------------------
            # Freeze Panes
            # ----------------------------------------------------------

            if ws.max_row > 5:

                ws.freeze_panes = "A5"

            # ----------------------------------------------------------
            # Auto Filter
            # ----------------------------------------------------------

            if ws.max_row >= 4 and ws.max_column > 1:

                ws.auto_filter.ref = ws.dimensions

            # ----------------------------------------------------------
            # Header Formatting
            # ----------------------------------------------------------

            if ws.max_row >= 4:

                for cell in ws[4]:

                    cell.fill = self.header_fill
                    cell.font = self.header_font
                    cell.border = self.border
                    cell.alignment = Alignment(
                        horizontal="center",
                        vertical="center"
                    )

            # ----------------------------------------------------------
            # Cell Formatting
            # ----------------------------------------------------------

            for row in ws.iter_rows():

                for cell in row:

                    cell.border = self.border

                    cell.alignment = Alignment(
                        vertical="top",
                        wrap_text=True
                    )

                    if cell.value is None:

                        continue

                    value = str(cell.value)

                    if value in ("Excellent", "Healthy"):

                        cell.fill = self.green_fill

                    elif value in ("Good", "Watch"):

                        cell.fill = self.yellow_fill

                    elif value in ("Critical", "At Risk"):

                        cell.fill = self.red_fill

                    elif value == "Low":

                        cell.fill = self.green_fill

                    elif value == "Medium":

                        cell.fill = self.yellow_fill

                    elif value == "High":

                        cell.fill = self.red_fill

                    elif value == "P1":

                        cell.fill = self.red_fill

                    elif value == "P2":

                        cell.fill = self.yellow_fill

                    elif value == "P3":

                        cell.fill = self.green_fill

            self.auto_width(ws)

        print("✓ Workbook Formatting Complete")

    # ==================================================================
    # Cover Page
    # ==================================================================

    def build_cover_page(self):

        print("Creating Cover Page...")

        ws = self.workbook.create_sheet(
            "About",
            0
        )

        ws.merge_cells("A1:H2")

        ws["A1"] = "SUPPORT INTELLIGENCE PLATFORM"

        ws["A1"].fill = self.title_fill

        ws["A1"].font = Font(
            size=22,
            bold=True,
            color="FFFFFF"
        )

        ws["A4"] = "Executive Support Intelligence Dashboard"

        ws["A4"].font = Font(
            size=18,
            bold=True
        )

        details = [

            ("Version", "4.1"),

            ("Generated", datetime.now().strftime("%d-%b-%Y %H:%M")),

            ("Platform", "Support Intelligence Platform"),

            ("Author", "Nischal"),

            ("Workbook", "Support_Intelligence_Dashboard.xlsx")

        ]

        row = 7

        for label, value in details:

            ws.cell(row=row, column=1, value=label).font = self.header_font

            ws.cell(row=row, column=2, value=value)

            row += 1

        ws["A14"] = "Description"

        ws["B14"] = (
            "Executive reporting platform built from "
            "Freshdesk Support Intelligence."
        )

        self.auto_width(ws)

    # ==================================================================
    # Table of Contents
    # ==================================================================

    def build_contents(self):

        print("Creating Table of Contents...")

        ws = self.workbook.create_sheet(
            "Contents",
            1
        )

        self.style_sheet(
            ws,
            "Workbook Contents"
        )

        ws["A4"] = "Worksheet"
        ws["B4"] = "Description"

        ws["A4"].fill = self.header_fill
        ws["B4"].fill = self.header_fill

        ws["A4"].font = self.header_font
        ws["B4"].font = self.header_font

        descriptions = {

            "Executive Summary": "Executive KPI Dashboard",

            "Analytics Index": "Analytics Datasets",

            "Executive Insights": "Business Insights",

            "Recommendations": "Recommendation Register",

            "Customer Health": "Customer Health Scores",

            "Renewal Risk": "Renewal Risk Assessment",

            "Voice of Customer": "Customer Feedback",

            "Engineering Dashboard": "Engineering Actions",

            "Product Dashboard": "Product Actions",

            "Customer Success Dashboard": "Customer Success Actions",

            "Finance Dashboard": "Finance Actions",

            "Support Dashboard": "Support Actions",

            "Executive Charts": "Executive Visualizations"

        }

        row = 5

        for sheet in self.workbook.sheetnames:

            if sheet in ("About", "Contents"):

                continue

            cell = ws.cell(
                row=row,
                column=1,
                value=sheet
            )

            cell.hyperlink = f"#{sheet}!A1"

            cell.style = "Hyperlink"

            ws.cell(
                row=row,
                column=2,
                value=descriptions.get(sheet, "")
            )

            row += 1

        self.auto_width(ws)

    # ==================================================================
    # Workbook Properties
    # ==================================================================

    def finalize_workbook(self):

        props = self.workbook.properties

        props.creator = "Support Intelligence Platform"

        props.title = "Support Intelligence Dashboard"

        props.subject = "Executive Reporting"

        props.category = "Business Intelligence"

        props.company = "Trinka AI"

        props.description = (
            "Freshdesk Executive Dashboard"
        )

    # ==================================================================
    # Save
    # ==================================================================

    def save(self):

        print("Saving Dashboard Workbook...")

        output = Path("output")

        output.mkdir(
            parents=True,
            exist_ok=True
        )

        filename = output / "Support_Intelligence_Dashboard.xlsx"

        self.workbook.save(filename)

        print(f"✓ Saved : {filename}")

        return filename

    # ==================================================================
    # Execute
    # ==================================================================

    def execute(self):

        print("\n" + "=" * 80)

        print("DASHBOARD BUILDER")

        print("=" * 80)

        self.build_executive_summary()

        self.build_analytics()

        self.build_business_reports()

        self.build_department_dashboards()

        self.build_chart_dashboard()

        self.build_business_charts()

        self.apply_conditional_formatting()

        self.build_cover_page()

        self.build_contents()

        self.finalize_workbook()

        self.save()

        print("\n✓ Dashboard Builder Completed Successfully")

        return self.workbook